<a href="https://colab.research.google.com/github/Mharis55/Data_Analytics_Bootcamp_2024/blob/main/machine_learning_class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('/content/NFLX.csv')

In [5]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2002-05-24,1.214286,1.225000,1.197143,1.210000,1.210000,11104800
1,2002-05-28,1.213571,1.232143,1.157143,1.157143,1.157143,6609400
2,2002-05-29,1.164286,1.164286,1.085714,1.103571,1.103571,6757800
3,2002-05-30,1.107857,1.107857,1.071429,1.071429,1.071429,10154200
4,2002-05-31,1.078571,1.078571,1.071429,1.076429,1.076429,8464400
...,...,...,...,...,...,...,...
5111,2022-09-13,226.500000,227.690002,217.720001,218.130005,218.130005,8000100
5112,2022-09-14,219.820007,228.000000,215.800003,224.119995,224.119995,8230300
5113,2022-09-15,230.470001,242.289993,229.100006,235.380005,235.380005,19454100
5114,2022-09-16,231.220001,241.360001,227.830002,240.130005,240.130005,18871600
5115,2022-09-19,245.050003,245.250000,235.750000,243.630005,243.630005,17895500

In [6]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [8]:
from statsmodels.tsa.arima.model import ARIMA

#fit model
model = ARIMA(df['High'], order=(5,1,0))
model_fit = model.fit()

#make prediction
forcast = model_fit.forecast(steps=12)
print(forcast)

5116    246.666439
5117    246.878853
5118    246.672138
5119    246.797628
5120    246.769293
5121    246.722718
5122    246.715467
5123    246.722534
5124    246.718176
5125    246.716785
5126    246.718063
5127    246.718377
Name: predicted_mean, dtype: float64